/** @typedef {{ plz: string, city: string }} PlzCity */

/** Häufige deutsche Vornamen (Auswahl, Workshop-Mock). */
export const FIRST_NAMES = [
  "Maria",
  "Anna",
  "Emma",
  "Sophia",
  "Marie",
  "Hannah",
  "Mia",
  "Emilia",
  "Lina",
  "Lea",
  "Johanna",
  "Amelie",
  "Charlotte",
  "Laura",
  "Leonie",
  "Clara",
  "Frieda",
  "Mathilda",
  "Luisa",
  "Ella",
  "Mila",
  "Leni",
  "Nora",
  "Ida",
  "Elena",
  "Lilly",
  "Maja",
  "Paula",
  "Marlene",
  "Elisa",
  "Ben",
  "Paul",
  "Leon",
  "Finn",
  "Elias",
  "Noah",
  "Luis",
  "Felix",
  "Jonas",
  "Luca",
  "Tim",
  "Max",
  "Moritz",
  "Julian",
  "Niklas",
  "David",
  "Tom",
  "Jan",
  "Simon",
  "Philipp",
  "Jakob",
  "Henry",
  "Theo",
  "Emil",
  "Anton",
  "Oskar",
  "Liam",
  "Matteo",
  "Samuel",
  "Alexander",
  "Florian",
  "Sebastian",
  "Tobias",
  "Christian",
  "Daniel",
  "Michael",
  "Thomas",
  "Andreas",
  "Stefan",
  "Martin",
  "Peter",
  "Markus",
  "Oliver",
  "Patrick",
  "Kevin",
  "Dennis",
  "Marcel",
  "Sven",
  "Jens",
  "Frank",
  "Klaus",
  "Wolfgang",
  "Heinz",
  "Günter",
  "Dieter",
  "Horst",
  "Manfred",
  "Ralf",
  "Uwe",
  "Bernd",
  "Jürgen",
  "Hans",
  "Karl",
  "Fritz",
  "Helmut",
  "Werner",
  "Gerhard",
  "Heike",
  "Sabine",
  "Petra",
  "Monika",
  "Andrea",
  "Susanne",
  "Birgit",
  "Gabriele",
  "Christine",
  "Brigitte",
  "Ursula",
  "Ingrid",
  "Renate",
  "Karin",
  "Anja",
  "Silke",
  "Nicole",
  "Stefanie",
  "Katrin",
  "Julia",
  "Sandra",
  "Melanie",
  "Jessica",
  "Jennifer",
  "Sarah",
  "Lisa",
  "Nadine",
  "Vanessa",
  "Michelle",
  "Diana",
  "Claudia",
  "Simone",
  "Tanja",
  "Kerstin",
  "Manuela",
  "Regina",
  "Astrid",
  "Ilse",
  "Erika",
  "Margot",
  "Hildegard",
  "Inge",
  "Lotte",
  "Greta",
  "Hedwig",
  "Trude",
  "Else",
  "Minna",
  "Anni",
  "Meta",
  "Lieschen",
  "Heidi",
  "Uschi",
  "Sigi",
  "Evi",
  "Rosi",
  "Gabi",
  "Uschi",
  "Hannelore",
  "Waltraud",
  "Edeltraud",
  "Roswitha",
  "Irmgard",
  "Marlies",
  "Annemarie",
  "Elke",
  "Beate",
  "Dagmar",
  "Jutta",
  "Irene",
  "Ruth",
  "Elisabeth",
  "Margarete",
  "Dorothea",
  "Wilhelmine",
  "Therese",
  "Magdalena",
  "Katharina",
  "Barbara",
  "Angelika",
  "Cornelia",
  "Bettina",
  "Heidemarie",
  "Marion",
  "Sylvia",
  "Yvonne",
  "Britta",
  "Corinna",
  "Ramona",
  "Sonja",
  "Carola",
  "Daniela",
  "Franziska",
  "Kathrin",
  "Larissa",
  "Miriam",
  "Nina",
  "Pamela",
  "Rebecca",
  "Theresa",
  "Vivien",
  "Wiebke",
  "Xenia",
  "Yasmin",
  "Zoe",
  "Alina",
  "Bianca",
  "Carina",
  "Denise",
  "Esther",
  "Fabienne",
  "Gina",
  "Helena",
  "Isabel",
  "Jana",
  "Kim",
  "Lara",
  "Mira",
  "Nele",
  "Olivia",
  "Pia",
  "Quinn",
  "Ronja",
  "Sina",
  "Tina",
  "Ulrike",
  "Vera",
  "Wanda",
  "Xaver",
  "Yannick",
  "Zita",
];

/** Häufige deutsche Nachnamen (Auswahl, Workshop-Mock). */
export const LAST_NAMES = [
  "Müller",
  "Schmidt",
  "Schneider",
  "Fischer",
  "Weber",
  "Meyer",
  "Wagner",
  "Becker",
  "Schulz",
  "Hoffmann",
  "Schäfer",
  "Koch",
  "Bauer",
  "Richter",
  "Klein",
  "Wolf",
  "Schröder",
  "Neumann",
  "Schwarz",
  "Zimmermann",
  "Braun",
  "Krüger",
  "Hofmann",
  "Hartmann",
  "Lange",
  "Schmitt",
  "Werner",
  "Schmitz",
  "Krause",
  "Meier",
  "Lehmann",
  "Schmid",
  "Schulze",
  "Maier",
  "Köhler",
  "Herrmann",
  "König",
  "Walter",
  "Mayer",
  "Huber",
  "Kaiser",
  "Fuchs",
  "Peters",
  "Lang",
  "Scholz",
  "Möller",
  "Weiß",
  "Jung",
  "Hahn",
  "Schubert",
  "Vogel",
  "Friedrich",
  "Keller",
  "Günther",
  "Frank",
  "Berger",
  "Winkler",
  "Roth",
  "Beck",
  "Lorenz",
  "Baumann",
  "Franke",
  "Albrecht",
  "Schuster",
  "Simon",
  "Ludwig",
  "Böhm",
  "Winter",
  "Kraus",
  "Martin",
  "Schumacher",
  "Krämer",
  "Vogt",
  "Stein",
  "Jäger",
  "Otto",
  "Sommer",
  "Groß",
  "Seidel",
  "Heinrich",
  "Brandt",
  "Haas",
  "Schreiber",
  "Graf",
  "Dietrich",
  "Ziegler",
  "Kuhn",
  "Pohl",
  "Engel",
  "Horn",
  "Busch",
  "Bergmann",
  "Thomas",
  "Voigt",
  "Sauer",
  "Arnold",
  "Wolff",
  "Pfeiffer",
  "Götz",
  "Seifert",
  "Lindner",
  "Ernst",
  "Hübner",
  "Kramer",
  "Franz",
  "Altmann",
  "Jansen",
  "Michel",
  "Bock",
  "Langer",
  "Wilke",
  "Schumann",
  "Kraft",
  "Wegner",
  "Förster",
  "Schulte",
  "Ott",
  "Reuter",
  "Beyer",
  "Grimm",
  "Barth",
  "Thiel",
  "Ullrich",
  "Hein",
  "Vetter",
  "Schade",
  "Faber",
  "Hennig",
  "Kirchner",
  "Brenner",
  "Hoppe",
  "Cordes",
  "Reinhardt",
  "Funk",
  "Hesse",
  "Riedel",
  "Rothe",
  "Herzog",
  "Ritter",
  "Neubert",
  "Kunz",
  "Schilling",
  "Blank",
  "Beier",
  "Kopp",
  "Hess",
  "Gruber",
  "Maurer",
  "Bender",
  "Schramm",
  "Nowak",
  "Hildebrandt",
  "Fritsch",
  "Klose",
  "John",
  "Stahl",
  "Henke",
  "Link",
  "Pfeifer",
  "Conrad",
  "Wirth",
  "Kern",
  "Heller",
  "Rau",
  "Eckert",
  "Sander",
  "Schindler",
  "Wetzel",
  "Hentschel",
  "Kiefer",
  "Jacobs",
  "Riedl",
  "Heinz",
  "Nolte",
  "Heß",
  "Fiedler",
  "Schenk",
  "Wenzel",
  "Hagemann",
  "Decker",
  "Junker",
  "Probst",
  "Baier",
  "Fröhlich",
  "Pick",
  "Hinrichs",
  "Kirsch",
  "Stoll",
  "Ebert",
  "Hinze",
  "Voss",
  "Steffen",
  "Heinze",
  "Falk",
  "Rupp",
  "Geiger",
  "Gärtner",
  "Buchholz",
  "Sattler",
  "Burger",
  "Hanke",
  "Lutz",
  "Scherer",
  "Reichert",
  "Moser",
  "Brandl",
  "Forster",
  "Abel",
  "Wolter",
  "Bartsch",
  "Wiese",
  "Marks",
  "Lindemann",
  "Kunze",
  "Mertens",
  "Stephan",
  "Arnold",
  "Haupt",
  "Bittner",
  "Adam",
  "Gross",
  "Hermann",
  "Schütte",
  "Döring",
  "Harms",
  "Bolz",
  "Kellner",
  "Schwab",
  "Timm",
  "Reichel",
  "Hinrichsen",
  "Stadler",
  "Fleischer",
  "Drews",
  "Siebert",
  "Kuhnert",
  "Mohr",
  "Heilmann",
  "Knapp",
  "Wegener",
  "Preuß",
  "Jost",
  "Martens",
  "Niemann",
  "Blum",
  "Hohmann",
  "Schober",
  "Körner",
  "Ehlers",
  "Adler",
  "Wulf",
  "Henn",
  "Wegner",
  "Stumpf",
  "Billhardt",
  "Bühler",
  "Dittrich",
  "Hartwig",
  "Kolb",
  "Schaefer",
  "Sell",
  "Urban",
  "Weller",
  "Zander",
  "Auer",
  "Bachmann",
  "Christ",
  "Dorn",
  "Eder",
  "Fink",
  "Geyer",
  "Hartl",
  "Ihle",
  "Jahn",
  "Kahl",
  "Lemke",
  "Metzger",
  "Nagel",
  "Opitz",
  "Plath",
  "Quandt",
  "Rasch",
  "Scharf",
  "Tiedemann",
  "Uhl",
  "Volk",
  "Wacker",
  "Yilmaz",
  "Zeller",
  "Aigner",
  "Bader",
  "Cramer",
  "Dürr",
  "Eichhorn",
  "Freitag",
  "Göbel",
  "Hacker",
  "Ismail",
  "Jakobs",
  "Kaufmann",
  "Löffler",
  "Meister",
  "Nitschke",
  "Orth",
  "Paulus",
  "Röder",
  "Schlegel",
  "Thomsen",
  "Unger",
  "Vogler",
  "Wegmann",
  "Zink",
];

/** Typische Straßennamen (Workshop-Mock). */
export const STREET_NAMES = [
  "Hauptstraße",
  "Bahnhofstraße",
  "Gartenstraße",
  "Schulstraße",
  "Dorfstraße",
  "Kirchstraße",
  "Lindenstraße",
  "Bergstraße",
  "Ringstraße",
  "Waldstraße",
  "Mühlenweg",
  "Schillerstraße",
  "Goethestraße",
  "Berliner Straße",
  "Hamburger Straße",
  "Münchener Straße",
  "Kölner Straße",
  "Frankfurter Straße",
  "Dresdner Straße",
  "Leipziger Straße",
  "Am Markt",
  "Am Park",
  "Am Bach",
  "Am See",
  "Am Hang",
  "An der Linde",
  "An der Kirche",
  "An der Schule",
  "Marktplatz",
  "Rathausplatz",
  "Schlossstraße",
  "Burgstraße",
  "Feldstraße",
  "Wiesenweg",
  "Ahornweg",
  "Buchenweg",
  "Eichenweg",
  "Rosenweg",
  "Sonnenweg",
  "Mondstraße",
  "Sternstraße",
  "Nordstraße",
  "Südstraße",
  "Oststraße",
  "Weststraße",
  "Industriestraße",
  "Gewerbestraße",
  "Fabrikstraße",
  "Werkstraße",
  "Hafenstraße",
  "Uferstraße",
  "Brückenstraße",
  "Talstraße",
  "Höhenstraße",
  "Panoramastraße",
  "Birkenallee",
  "Eichenallee",
  "Tannenweg",
  "Fichtenstraße",
  "Kastanienstraße",
  "Ulmenstraße",
  "Pappelweg",
  "Weidenweg",
  "Jägerstraße",
  "Försterweg",
  "Bäckerstraße",
  "Müllerweg",
  "Schmiedegasse",
  "Handwerkerstraße",
  "Meisterstraße",
  "Neue Straße",
  "Alte Straße",
  "Breite Straße",
  "Enge Gasse",
  "Lange Straße",
  "Kurze Gasse",
  "Hohe Straße",
  "Tiefe Straße",
  "Stille Straße",
  "Friedensstraße",
  "Freiheitsstraße",
  "Einheitstraße",
  "Lessingstraße",
  "Heinrich-Heine-Straße",
  "Mozartstraße",
  "Beethovenstraße",
  "Bachstraße",
  "Händelstraße",
  "Richard-Wagner-Straße",
  "Humboldtstraße",
  "Kantstraße",
  "Hegelstraße",
  "Nietzschestraße",
  "Max-Planck-Straße",
  "Albert-Einstein-Straße",
  "Martin-Luther-Straße",
  "Wilhelmstraße",
  "Friedrichstraße",
  "Kaiserstraße",
  "Königsallee",
  "Prinzregentenstraße",
  "Ludwigstraße",
  "Leopoldstraße",
  "Maximilianstraße",
  "Karolinenstraße",
  "Elisabethenstraße",
  "Margaretenstraße",
  "Johannisstraße",
  "Petersstraße",
  "Marienstraße",
  "Josefstraße",
  "Antoniusstraße",
  "Barbarastraße",
  "Katharinenstraße",
  "Nikolausstraße",
  "Stephanstraße",
  "Laurentiusstraße",
  "Bonifatiusstraße",
  "Gregorstraße",
  "Dominikusstraße",
  "Franziskusweg",
  "Klosterstraße",
  "Kapellenweg",
  "Pfarrgasse",
  "Kirchenweg",
  "Friedhofsweg",
  "Sportplatzweg",
  "Stadionstraße",
  "Turnhallenweg",
  "Schwimmbadstraße",
  "Freibadweg",
  "Kurparkstraße",
  "Thermenstraße",
  "Klinikstraße",
  "Krankenhausstraße",
  "Apothekenstraße",
  "Ärztehausstraße",
  "Poststraße",
  "Telegrafenstraße",
  "Busbahnhofstraße",
  "Flughafenallee",
  "Autobahnstraße",
  "Bundesstraße",
  "Landstraße",
  "Feldweg",
  "Schotterweg",
  "Reihenhausweg",
  "Siedlung",
  "Wohnpark",
  "Gewerbepark",
  "Technologiepark",
  "Innovationsallee",
  "Digitalstraße",
  "Cloudweg",
  "Serverstraße",
  "Datenweg",
  "Workshopallee",
];

/**
 * Echte PLZ→Ort-Paare (Auszug, für realistische Adressen).
 * @type {PlzCity[]}
 */
export const PLZ_CITIES = [
  { plz: "10115", city: "Berlin" },
  { plz: "10117", city: "Berlin" },
  { plz: "10178", city: "Berlin" },
  { plz: "10243", city: "Berlin" },
  { plz: "10318", city: "Berlin" },
  { plz: "10405", city: "Berlin" },
  { plz: "10551", city: "Berlin" },
  { plz: "10623", city: "Berlin" },
  { plz: "10707", city: "Berlin" },
  { plz: "10823", city: "Berlin" },
  { plz: "10961", city: "Berlin" },
  { plz: "12043", city: "Berlin" },
  { plz: "12101", city: "Berlin" },
  { plz: "12203", city: "Berlin" },
  { plz: "12347", city: "Berlin" },
  { plz: "12435", city: "Berlin" },
  { plz: "12555", city: "Berlin" },
  { plz: "12679", city: "Berlin" },
  { plz: "13051", city: "Berlin" },
  { plz: "13125", city: "Berlin" },
  { plz: "13347", city: "Berlin" },
  { plz: "13407", city: "Berlin" },
  { plz: "13503", city: "Berlin" },
  { plz: "14050", city: "Berlin" },
  { plz: "20095", city: "Hamburg" },
  { plz: "20144", city: "Hamburg" },
  { plz: "20249", city: "Hamburg" },
  { plz: "20354", city: "Hamburg" },
  { plz: "20457", city: "Hamburg" },
  { plz: "20535", city: "Hamburg" },
  { plz: "21029", city: "Hamburg" },
  { plz: "22041", city: "Hamburg" },
  { plz: "22143", city: "Hamburg" },
  { plz: "22303", city: "Hamburg" },
  { plz: "22415", city: "Hamburg" },
  { plz: "22523", city: "Hamburg" },
  { plz: "22761", city: "Hamburg" },
  { plz: "80331", city: "München" },
  { plz: "80335", city: "München" },
  { plz: "80469", city: "München" },
  { plz: "80538", city: "München" },
  { plz: "80636", city: "München" },
  { plz: "80796", city: "München" },
  { plz: "80801", city: "München" },
  { plz: "80992", city: "München" },
  { plz: "81241", city: "München" },
  { plz: "81369", city: "München" },
  { plz: "81476", city: "München" },
  { plz: "81667", city: "München" },
  { plz: "81735", city: "München" },
  { plz: "81825", city: "München" },
  { plz: "81925", city: "München" },
  { plz: "50667", city: "Köln" },
  { plz: "50668", city: "Köln" },
  { plz: "50733", city: "Köln" },
  { plz: "50823", city: "Köln" },
  { plz: "50931", city: "Köln" },
  { plz: "51061", city: "Köln" },
  { plz: "51103", city: "Köln" },
  { plz: "60311", city: "Frankfurt am Main" },
  { plz: "60313", city: "Frankfurt am Main" },
  { plz: "60318", city: "Frankfurt am Main" },
  { plz: "60325", city: "Frankfurt am Main" },
  { plz: "60486", city: "Frankfurt am Main" },
  { plz: "60528", city: "Frankfurt am Main" },
  { plz: "60596", city: "Frankfurt am Main" },
  { plz: "65929", city: "Frankfurt am Main" },
  { plz: "70173", city: "Stuttgart" },
  { plz: "70174", city: "Stuttgart" },
  { plz: "70178", city: "Stuttgart" },
  { plz: "70327", city: "Stuttgart" },
  { plz: "70469", city: "Stuttgart" },
  { plz: "70563", city: "Stuttgart" },
  { plz: "70629", city: "Stuttgart" },
  { plz: "40210", city: "Düsseldorf" },
  { plz: "40211", city: "Düsseldorf" },
  { plz: "40213", city: "Düsseldorf" },
  { plz: "40476", city: "Düsseldorf" },
  { plz: "40545", city: "Düsseldorf" },
  { plz: "44135", city: "Dortmund" },
  { plz: "44137", city: "Dortmund" },
  { plz: "44141", city: "Dortmund" },
  { plz: "45127", city: "Essen" },
  { plz: "45128", city: "Essen" },
  { plz: "45131", city: "Essen" },
  { plz: "04103", city: "Leipzig" },
  { plz: "04105", city: "Leipzig" },
  { plz: "04109", city: "Leipzig" },
  { plz: "04229", city: "Leipzig" },
  { plz: "01067", city: "Dresden" },
  { plz: "01069", city: "Dresden" },
  { plz: "01097", city: "Dresden" },
  { plz: "01127", city: "Dresden" },
  { plz: "30159", city: "Hannover" },
  { plz: "30161", city: "Hannover" },
  { plz: "30163", city: "Hannover" },
  { plz: "30419", city: "Hannover" },
  { plz: "28195", city: "Bremen" },
  { plz: "28203", city: "Bremen" },
  { plz: "28209", city: "Bremen" },
  { plz: "28307", city: "Bremen" },
  { plz: "90402", city: "Nürnberg" },
  { plz: "90403", city: "Nürnberg" },
  { plz: "90408", city: "Nürnberg" },
  { plz: "90491", city: "Nürnberg" },
  { plz: "86150", city: "Augsburg" },
  { plz: "86152", city: "Augsburg" },
  { plz: "86159", city: "Augsburg" },
  { plz: "68159", city: "Mannheim" },
  { plz: "68161", city: "Mannheim" },
  { plz: "68163", city: "Mannheim" },
  { plz: "76131", city: "Karlsruhe" },
  { plz: "76133", city: "Karlsruhe" },
  { plz: "76137", city: "Karlsruhe" },
  { plz: "79102", city: "Freiburg im Breisgau" },
  { plz: "79104", city: "Freiburg im Breisgau" },
  { plz: "79110", city: "Freiburg im Breisgau" },
  { plz: "93047", city: "Regensburg" },
  { plz: "93049", city: "Regensburg" },
  { plz: "93053", city: "Regensburg" },
  { plz: "96047", city: "Bamberg" },
  { plz: "96049", city: "Bamberg" },
  { plz: "97070", city: "Würzburg" },
  { plz: "97072", city: "Würzburg" },
  { plz: "99084", city: "Erfurt" },
  { plz: "99085", city: "Erfurt" },
  { plz: "99086", city: "Erfurt" },
  { plz: "39104", city: "Magdeburg" },
  { plz: "39106", city: "Magdeburg" },
  { plz: "39108", city: "Magdeburg" },
  { plz: "06108", city: "Halle (Saale)" },
  { plz: "06110", city: "Halle (Saale)" },
  { plz: "06112", city: "Halle (Saale)" },
  { plz: "04177", city: "Leipzig" },
  { plz: "04315", city: "Leipzig" },
  { plz: "18055", city: "Rostock" },
  { plz: "18057", city: "Rostock" },
  { plz: "18059", city: "Rostock" },
  { plz: "23552", city: "Lübeck" },
  { plz: "23554", city: "Lübeck" },
  { plz: "23558", city: "Lübeck" },
  { plz: "24103", city: "Kiel" },
  { plz: "24105", city: "Kiel" },
  { plz: "24109", city: "Kiel" },
  { plz: "49074", city: "Osnabrück" },
  { plz: "49076", city: "Osnabrück" },
  { plz: "49078", city: "Osnabrück" },
  { plz: "48143", city: "Münster" },
  { plz: "48145", city: "Münster" },
  { plz: "48147", city: "Münster" },
  { plz: "33602", city: "Bielefeld" },
  { plz: "33604", city: "Bielefeld" },
  { plz: "33609", city: "Bielefeld" },
  { plz: "33100", city: "Paderborn" },
  { plz: "33102", city: "Paderborn" },
  { plz: "33104", city: "Paderborn" },
  { plz: "52062", city: "Aachen" },
  { plz: "52064", city: "Aachen" },
  { plz: "52066", city: "Aachen" },
  { plz: "53111", city: "Bonn" },
  { plz: "53113", city: "Bonn" },
  { plz: "53115", city: "Bonn" },
  { plz: "55116", city: "Mainz" },
  { plz: "55118", city: "Mainz" },
  { plz: "55120", city: "Mainz" },
  { plz: "65183", city: "Wiesbaden" },
  { plz: "65185", city: "Wiesbaden" },
  { plz: "65187", city: "Wiesbaden" },
  { plz: "64283", city: "Darmstadt" },
  { plz: "64285", city: "Darmstadt" },
  { plz: "64287", city: "Darmstadt" },
  { plz: "35390", city: "Gießen" },
  { plz: "35392", city: "Gießen" },
  { plz: "35394", city: "Gießen" },
  { plz: "34117", city: "Kassel" },
  { plz: "34119", city: "Kassel" },
  { plz: "34121", city: "Kassel" },
  { plz: "37073", city: "Göttingen" },
  { plz: "37075", city: "Göttingen" },
  { plz: "37077", city: "Göttingen" },
  { plz: "38100", city: "Braunschweig" },
  { plz: "38102", city: "Braunschweig" },
  { plz: "38104", city: "Braunschweig" },
  { plz: "31134", city: "Hildesheim" },
  { plz: "31137", city: "Hildesheim" },
  { plz: "31139", city: "Hildesheim" },
  { plz: "21335", city: "Lüneburg" },
  { plz: "21337", city: "Lüneburg" },
  { plz: "21339", city: "Lüneburg" },
  { plz: "27472", city: "Cuxhaven" },
  { plz: "27474", city: "Cuxhaven" },
  { plz: "27476", city: "Cuxhaven" },
  { plz: "26121", city: "Oldenburg" },
  { plz: "26122", city: "Oldenburg" },
  { plz: "26125", city: "Oldenburg" },
  { plz: "27568", city: "Bremerhaven" },
  { plz: "27570", city: "Bremerhaven" },
  { plz: "27572", city: "Bremerhaven" },
  { plz: "47798", city: "Krefeld" },
  { plz: "47800", city: "Krefeld" },
  { plz: "47802", city: "Krefeld" },
  { plz: "47051", city: "Duisburg" },
  { plz: "47053", city: "Duisburg" },
  { plz: "47055", city: "Duisburg" },
  { plz: "42103", city: "Wuppertal" },
  { plz: "42105", city: "Wuppertal" },
  { plz: "42107", city: "Wuppertal" },
  { plz: "44787", city: "Bochum" },
  { plz: "44789", city: "Bochum" },
  { plz: "44791", city: "Bochum" },
  { plz: "58089", city: "Hagen" },
  { plz: "58091", city: "Hagen" },
  { plz: "58093", city: "Hagen" },
  { plz: "59063", city: "Hamm" },
  { plz: "59065", city: "Hamm" },
  { plz: "59067", city: "Hamm" },
  { plz: "33098", city: "Paderborn" },
  { plz: "33330", city: "Gütersloh" },
  { plz: "33332", city: "Gütersloh" },
  { plz: "33334", city: "Gütersloh" },
  { plz: "59069", city: "Hamm" },
  { plz: "59423", city: "Unna" },
  { plz: "59425", city: "Unna" },
  { plz: "59427", city: "Unna" },
  { plz: "45879", city: "Gelsenkirchen" },
  { plz: "45881", city: "Gelsenkirchen" },
  { plz: "45883", city: "Gelsenkirchen" },
  { plz: "45468", city: "Mülheim an der Ruhr" },
  { plz: "45470", city: "Mülheim an der Ruhr" },
  { plz: "45472", city: "Mülheim an der Ruhr" },
  { plz: "41061", city: "Mönchengladbach" },
  { plz: "41063", city: "Mönchengladbach" },
  { plz: "41065", city: "Mönchengladbach" },
  { plz: "47829", city: "Krefeld" },
  { plz: "47839", city: "Krefeld" },
  { plz: "47807", city: "Krefeld" },
  { plz: "85049", city: "Ingolstadt" },
  { plz: "85051", city: "Ingolstadt" },
  { plz: "85053", city: "Ingolstadt" },
  { plz: "84028", city: "Landshut" },
  { plz: "84030", city: "Landshut" },
  { plz: "84032", city: "Landshut" },
  { plz: "94469", city: "Deggendorf" },
  { plz: "94471", city: "Deggendorf" },
  { plz: "94473", city: "Deggendorf" },
  { plz: "87435", city: "Kempten (Allgäu)" },
  { plz: "87437", city: "Kempten (Allgäu)" },
  { plz: "87439", city: "Kempten (Allgäu)" },
  { plz: "88045", city: "Friedrichshafen" },
  { plz: "88046", city: "Friedrichshafen" },
  { plz: "88048", city: "Friedrichshafen" },
  { plz: "89073", city: "Ulm" },
  { plz: "89075", city: "Ulm" },
  { plz: "89077", city: "Ulm" },
  { plz: "72764", city: "Reutlingen" },
  { plz: "72766", city: "Reutlingen" },
  { plz: "72768", city: "Reutlingen" },
  { plz: "74072", city: "Heilbronn" },
  { plz: "74074", city: "Heilbronn" },
  { plz: "74076", city: "Heilbronn" },
  { plz: "71634", city: "Ludwigsburg" },
  { plz: "71636", city: "Ludwigsburg" },
  { plz: "71638", city: "Ludwigsburg" },
  { plz: "68167", city: "Mannheim" },
  { plz: "68169", city: "Mannheim" },
  { plz: "69115", city: "Heidelberg" },
  { plz: "69117", city: "Heidelberg" },
  { plz: "69121", city: "Heidelberg" },
  { plz: "77652", city: "Offenburg" },
  { plz: "77654", city: "Offenburg" },
  { plz: "77656", city: "Offenburg" },
  { plz: "78462", city: "Konstanz" },
  { plz: "78464", city: "Konstanz" },
  { plz: "78467", city: "Konstanz" },
  { plz: "88212", city: "Ravensburg" },
  { plz: "88213", city: "Ravensburg" },
  { plz: "88214", city: "Ravensburg" },
  { plz: "89079", city: "Ulm" },
  { plz: "89081", city: "Ulm" },
  { plz: "89090", city: "Ulm" },
  { plz: "97080", city: "Würzburg" },
  { plz: "97082", city: "Würzburg" },
  { plz: "97084", city: "Würzburg" },
  { plz: "96050", city: "Bamberg" },
  { plz: "96052", city: "Bamberg" },
  { plz: "90762", city: "Fürth" },
  { plz: "90763", city: "Fürth" },
  { plz: "90765", city: "Fürth" },
  { plz: "91052", city: "Erlangen" },
  { plz: "91054", city: "Erlangen" },
  { plz: "91056", city: "Erlangen" },
  { plz: "85055", city: "Ingolstadt" },
  { plz: "85057", city: "Ingolstadt" },
  { plz: "85059", city: "Ingolstadt" },
  { plz: "93059", city: "Regensburg" },
  { plz: "93057", city: "Regensburg" },
  { plz: "93055", city: "Regensburg" },
  { plz: "84034", city: "Landshut" },
  { plz: "84036", city: "Landshut" },
  { plz: "94474", city: "Deggendorf" },
  { plz: "94475", city: "Deggendorf" },
  { plz: "94476", city: "Deggendorf" },
  { plz: "87463", city: "Kempten (Allgäu)" },
  { plz: "87464", city: "Kempten (Allgäu)" },
  { plz: "87465", city: "Kempten (Allgäu)" },
  { plz: "88069", city: "Friedrichshafen" },
  { plz: "88070", city: "Friedrichshafen" },
  { plz: "88071", city: "Friedrichshafen" },
  { plz: "72793", city: "Reutlingen" },
  { plz: "72794", city: "Reutlingen" },
  { plz: "72795", city: "Reutlingen" },
  { plz: "74078", city: "Heilbronn" },
  { plz: "74080", city: "Heilbronn" },
  { plz: "74081", city: "Heilbronn" },
  { plz: "71640", city: "Ludwigsburg" },
  { plz: "71642", city: "Ludwigsburg" },
  { plz: "71643", city: "Ludwigsburg" },
  { plz: "68199", city: "Mannheim" },
  { plz: "68219", city: "Mannheim" },
  { plz: "68229", city: "Mannheim" },
  { plz: "69123", city: "Heidelberg" },
  { plz: "69124", city: "Heidelberg" },
  { plz: "69126", city: "Heidelberg" },
  { plz: "77694", city: "Offenburg" },
  { plz: "77695", city: "Offenburg" },
  { plz: "77696", city: "Offenburg" },
  { plz: "78476", city: "Konstanz" },
  { plz: "78477", city: "Konstanz" },
  { plz: "78478", city: "Konstanz" },
  { plz: "88239", city: "Ravensburg" },
  { plz: "88240", city: "Ravensburg" },
  { plz: "88241", city: "Ravensburg" },
];

/**
 * Produktkatalog im Stil eines Kaffee-/Versandhändlers (Workshop-Mock, nicht live von retail-catalog).
 * @type {{ id: string, title: string, price: string, category: string }[]}
 */
export const CATALOG_PRODUCTS = [
  { id: "SKU-100001", title: "Privat Kaffee Klassisch, ganze Bohne 1 kg", price: "12.99", category: "Kaffee" },
  { id: "SKU-100002", title: "Privat Kaffee Kräftig, gemahlen 500 g", price: "7.49", category: "Kaffee" },
  { id: "SKU-100003", title: "Espresso Milano, ganze Bohne 1 kg", price: "14.99", category: "Kaffee" },
  { id: "SKU-100004", title: "Cafissimo Espresso, 96 Kapseln", price: "24.99", category: "Kapseln" },
  { id: "SKU-100005", title: "Cafissimo Caffè Crema, 96 Kapseln", price: "24.99", category: "Kapseln" },
  { id: "SKU-100006", title: "Entkoffeinierter Kaffee, gemahlen 500 g", price: "6.99", category: "Kaffee" },
  { id: "SKU-100007", title: "Brazil Mild, ganze Bohne 500 g", price: "8.49", category: "Kaffee" },
  { id: "SKU-100008", title: "Colombia Finest, Filter 500 g", price: "9.49", category: "Kaffee" },
  { id: "SKU-100009", title: "Kenya AA, ganze Bohne 500 g", price: "10.99", category: "Kaffee" },
  { id: "SKU-100010", title: "Guatemala Huehuetenango, 500 g", price: "11.49", category: "Kaffee" },
  { id: "SKU-100011", title: "Barista Caffè Crema, 1 kg", price: "15.99", category: "Kaffee" },
  { id: "SKU-100012", title: "Qbo Kaffee Peru, 500 g", price: "9.99", category: "Kaffee" },
  { id: "SKU-100013", title: "Qbo Kaffee Äthiopien, 500 g", price: "10.49", category: "Kaffee" },
  { id: "SKU-100014", title: "Eduscho Gala, gemahlen 500 g", price: "7.99", category: "Kaffee" },
  { id: "SKU-100015", title: "Eduscho Gala, ganze Bohne 1 kg", price: "13.49", category: "Kaffee" },
  { id: "SKU-100016", title: "Cafissimo Maschine Picco, schwarz", price: "59.99", category: "Kaffeemaschinen" },
  { id: "SKU-100017", title: "Cafissimo Maschine Compact, weiß", price: "49.99", category: "Kaffeemaschinen" },
  { id: "SKU-100018", title: "Esperto Caffè Kaffeemaschine, Edelstahl", price: "89.99", category: "Kaffeemaschinen" },
  { id: "SKU-100019", title: "French Press, 1 Liter", price: "19.99", category: "Zubehör" },
  { id: "SKU-100020", title: "Milchaufschäumer To Go", price: "29.99", category: "Zubehör" },
  { id: "SKU-100021", title: "Tee Grüner Tee Sencha, 20 Beutel", price: "3.49", category: "Tee" },
  { id: "SKU-100022", title: "Tee Earl Grey, 25 Beutel", price: "3.99", category: "Tee" },
  { id: "SKU-100023", title: "Tee Kräutergarten Fenchel-Anis, 20 Beutel", price: "3.49", category: "Tee" },
  { id: "SKU-100024", title: "Tee Früchtetraum, 20 Beutel", price: "3.99", category: "Tee" },
  { id: "SKU-100025", title: "Tee Pfefferminze, 25 Beutel", price: "3.49", category: "Tee" },
  { id: "SKU-100026", title: "Kakao Trinkschokolade, 500 g", price: "4.99", category: "Kakao" },
  { id: "SKU-100027", title: "Vollmilch-Schokolade 100 g", price: "1.99", category: "Schokolade" },
  { id: "SKU-100028", title: "Edelherb 70 %, 100 g", price: "2.29", category: "Schokolade" },
  { id: "SKU-100029", title: "Nougat Minis, 125 g", price: "2.49", category: "Süßes" },
  { id: "SKU-100030", title: "Butterkekse, 200 g", price: "2.99", category: "Gebäck" },
  { id: "SKU-100031", title: "Haferkekse Schokolade, 175 g", price: "2.79", category: "Gebäck" },
  { id: "SKU-100032", title: "Müsli Knusper Früchte, 500 g", price: "4.49", category: "Frühstück" },
  { id: "SKU-100033", title: "Konfitüre Erdbeere Extra, 340 g", price: "2.99", category: "Frühstück" },
  { id: "SKU-100034", title: "Olivenöl Extra Vergine, 750 ml", price: "9.99", category: "Speiseöl" },
  { id: "SKU-100035", title: "Tomatensauce Basilico, 500 ml", price: "2.49", category: "Vorräte" },
  { id: "SKU-100036", title: "Pasta Spaghetti No. 5, 500 g", price: "1.49", category: "Vorräte" },
  { id: "SKU-100037", title: "Gewürzmühle Pfeffer schwarz", price: "4.99", category: "Gewürze" },
  { id: "SKU-100038", title: "Gewürzmühle Meersalz", price: "3.99", category: "Gewürze" },
  { id: "SKU-100039", title: "Reinigungstabletten Cafissimo, 10 Stück", price: "5.99", category: "Zubehör" },
  { id: "SKU-100040", title: "Entkalker flüssig, 500 ml", price: "4.49", category: "Zubehör" },
  { id: "SKU-100041", title: "Thermobecher To Go, 0,4 l", price: "14.99", category: "Zubehör" },
  { id: "SKU-100042", title: "Kaffeefilter Größe 4, 80 Stück", price: "2.99", category: "Zubehör" },
  { id: "SKU-100043", title: "Bio Filterkaffee, 500 g", price: "8.99", category: "Kaffee" },
  { id: "SKU-100044", title: "Bio Espresso, 500 g", price: "9.49", category: "Kaffee" },
  { id: "SKU-100045", title: "Handtuch Set, 2-teilig, anthrazit", price: "24.99", category: "Wohnen" },
  { id: "SKU-100046", title: "Bettwäsche Renforcé, 135x200 cm", price: "39.99", category: "Wohnen" },
  { id: "SKU-100047", title: "Hemd Regular Fit, weiß", price: "29.99", category: "Mode" },
  { id: "SKU-100048", title: "Jeans Straight, dunkelblau", price: "49.99", category: "Mode" },
  { id: "SKU-100049", title: "Sneaker Leder, navy", price: "59.99", category: "Mode" },
  { id: "SKU-100050", title: "Mobilfunk Flat S", price: "9.99", category: "Mobilfunk" },
  { id: "SKU-100051", title: "Mobilfunk Flat M", price: "14.99", category: "Mobilfunk" },
  { id: "SKU-100052", title: "Reisekoffer Hartschale M", price: "89.99", category: "Reise" },
  { id: "SKU-100053", title: "Rucksack City, schwarz", price: "39.99", category: "Reise" },
  { id: "SKU-100054", title: "Regenschirm automatisch", price: "19.99", category: "Accessoires" },
  { id: "SKU-100055", title: "Sonnenbrille polarisiert", price: "34.99", category: "Accessoires" },
  { id: "SKU-100056", title: "Wein Merlot trocken, 0,75 l", price: "5.99", category: "Wein" },
  { id: "SKU-100057", title: "Wein Riesling halbtrocken, 0,75 l", price: "6.49", category: "Wein" },
  { id: "SKU-100058", title: "Sekt Brut, 0,75 l", price: "7.99", category: "Wein" },
  { id: "SKU-100059", title: "Prosecco DOC, 0,75 l", price: "6.99", category: "Wein" },
  { id: "SKU-100060", title: "Geschenkset Kaffee Genuss", price: "29.99", category: "Geschenke" },
];

export const WAREHOUSES = ["BER", "HAM", "MUC", "CGN", "FRA", "LEJ", "DUS", "STR"];
